w3xforum/authentication/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = "auth"
urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('register/', views.user_registration, name='register'),
    path('register/activation/<str:user_name>/', views.user_activation, name='activation'),
    path('password_recovery/', views.password_recovery, name='pswrdrec_mail'),
    path('password_recovery/<str:user_name>', views.password_recovery_code, name='pswrdrec_code'),
    path('password_recovery/<str:user_name>/complete', views.password_recovery_complete, name='pswrdrec_complete'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

w3xforum/posts/urls.py
from django.urls import path, include
from . import views

app_name = "posts"
urlpatterns = [
    path('', views.PostsList.as_view(), name="posts_list"),
    path('add/', views.post_add, name="post_add"),
    path('<slug:category_slug>/<int:post_pk>/', views.PostDetail.as_view(), name="post_detail"),
    path('categories/', views.CategoryList.as_view(), name="categories_list"),
    path('<slug:category_slug>/', views.category_detail, name="category_detail"),
]

w3xforum/w3xforum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth.views import LogoutView


app_name = 'home'
urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('auth/', include('authentication.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

w3xforum/templates/_inc/_cat_navbar.html
{% load posts_tags_filters %}
<style>
  #cat_nav {
    background-color: #252525;
    -webkit-box-shadow: 0px 8px 10px 2px rgba(34, 60, 80, 0.2);
    -moz-box-shadow: 0px 8px 10px 2px rgba(34, 60, 80, 0.2);
    box-shadow: 0px 8px 10px 2px rgba(34, 60, 80, 0.2);
  }
  .cat_a {
    color: #2EC077;
    text-decoration: none;
    text-transform: uppercase;
  }

  .cat_a:hover {
    color: #2C9762;
  }

  .cat_nav_wrapper {
    display: flex;
    flex-flow: row nowrap;
    justify-content: space-around;
  }
</style>
<div id="cat_nav" class="container_fluid">
  <div class="row">
    <div class="cat_nav_wrapper">
      {% for category in categories %}
        <div>
          <a class="cat_a" href="{{ category.get_absolute_url }}">{{ category.name }}({{ category|count_is_published }})</a>
        </div>
      {% endfor %}
      <div>
        <a class="cat_a" href="{% url 'posts:categories_list' %}">Все категории...</a>
      </div>
    </div>
  </div>
</div>

w3xforum/templates/_inc/_navbar.html
<nav class="nav">
  <div class="container-fluid">
    <a href="#" class="navbar-logo">W3Xforum</a>
    <div class="navbar-wrap">
      <ul class="navbar-menu" style="margin: auto;">
        <li>
          <a class="navbar-ref" href="/">Главная</a>
        </li>
        <li>
          <a class="navbar-ref" href="{% url 'posts:posts_list' %}">Посты</a>
        </li>
        <li>
          <a class="navbar-ref" href="{% url 'posts:post_add' %}">Предложить пост</a>
        </li>
      </ul>
      <div class="nav-user-menu">
        {% if user.is_authenticated %}
          <a class="nav-user-ref" href="{% url 'auth:logout' %}" alt="-">Выход</a>
          <a href="#" alt="-"><img class="nav-user-avatar" src="{{ user.avatar.url }}" alt="-"></a>
        {% else %}
          <a class="nav-user-ref" href="{% url 'auth:login' %}" alt="-">Вход</a>
          <a class="nav-user-ref" href="{% url 'auth:register' %}" alt="-">Регистрация</a>
        {% endif %}
      </div>
    </div>
  </div>
</nav>

w3xforum/templates/_inc/_posts_paginator.html
<div class="container-fluid">
  <div class="col">
    {% if page_obj.has_other_pages %}
      <nav>
        <ul class="pagination justify-content-center">
          {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
          {% else %}
                <li class="page-item disabled"><a class="page-link">&laquo;</a></li>
          {% endif %}
          {% for p in page_obj.paginator.page_range %}
            {% if page_obj.number == p %}
              <li class="page-item active" aria-current="page"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
            {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
              <li class="page-item"><a class="page-link" href="?page={{ p }}" alt="-">{{ p }}</a></li>
            {% endif %}
          {% endfor %}
          {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
          {% else %}
                <li class="page-item disabled"><a class="page-link">&raquo;</a></li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}
  </div>
</div>