w3xforum/posts/urls.py
from django.urls import path, include
from . import views

app_name = "posts"
urlpatterns = [
    path('', views.PostsList.as_view(), name="posts_list"),
    path('add/', views.post_add, name="post_add"),
    path('<slug:category_slug>/<int:post_pk>/', views.PostDetail.as_view(), name="post_detail"),
    path('categories/', views.CategoryList.as_view(), name="categories_list"),
    path('<slug:category_slug>/', views.category_detail, name="category_detail"),
]

w3xforum/w3xforum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth.views import LogoutView


app_name = 'home'
urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('auth/', include('authentication.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

w3xforum/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True, db_index=True, verbose_name="Название категории")
    slug = models.SlugField(max_length=50, unique=True, db_index=True, verbose_name="URL")

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ["name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("posts:category_detail", kwargs={"category_slug": self.slug})

def get_img_path(instance, filename):
    return "posts/%s" % (filename)


class Post(models.Model):
    title = models.CharField(max_length=90, verbose_name="Название", db_index=True, unique=True)
    content = models.TextField(db_index=True, verbose_name="Описание")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Категория")
    author = models.ForeignKey(get_user_model(), blank=True, on_delete=models.CASCADE, verbose_name="Автор")
    is_published = models.BooleanField(default=False, verbose_name="Пост опубликован")
    published = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Дата публикации")
    edited = models.DateTimeField(auto_now=True, verbose_name="Дата редактирования")

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"
        ordering = ["-published", 'category', 'title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:post_detail", kwargs={
            "category_slug": self.category.slug,
            "post_pk": self.pk,
        })

    def trim50_title(self):
        return u"%s..." % (self.title[:50],)

    def trim50_content(self):
        return u"%s..." % (self.content[:50],)


class Image(models.Model):
    post = models.ForeignKey(Post, default=None, on_delete=models.CASCADE)
    imgs = models.ImageField(upload_to=get_img_path, blank=True, verbose_name="Изображения")

w3xforum/posts/forms.py
from django import forms
from django.core import validators
from .models import Post, Category

class PostForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), label='Категория',
                                      widget=forms.Select(attrs={'placeholder': 'Категория', 'style': 'border-radius: 5px;border-width: thin;padding: 5px;'}))
    title = forms.CharField(label='Название', widget=forms.widgets.TextInput(
        attrs={'placeholder': 'Название', 'style': 'border-radius: 5px;border-width: thin;padding: 5px;'}),
                            validators=[validators.MinLengthValidator(8)], error_messages= {
        "min_length": "Слишком короткое название!"
    })
    content = forms.CharField(label='Текст', widget=forms.widgets.Textarea(
        attrs={'placeholder': 'Текст', 'style': 'border-radius: 5px;border-width: thin;padding: 5px;'}),
                              validators=[validators.MinLengthValidator(8)],
                              error_messages= {
        "min_length": "Слишком короткое описание!"
    })
    imgs = forms.FileField(label='Изображения', widget=forms.ClearableFileInput(attrs={'multiple': True}))

    class Meta:
        model = Post
        fields = ('category', 'title', 'content', 'imgs')

w3xforum/posts/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from .models import Post, Category, Image
from .forms import PostForm
from django.core.paginator import Paginator



class PostsList(ListView):
    queryset = Post.objects.filter(is_published=True)
    paginate_by = 3
    template_name = "posts/posts_list.html"


class PostDetail(DetailView):
    queryset = Post.objects.all()
    context_object_name = 'current_post'
    template_name = 'posts/post_detail.html'

    def get_object(self, queryset=None):
        slug = self.kwargs.get('category_slug', None)
        pk = self.kwargs.get('post_pk', None)
        try:
            return Post.objects.get(category__slug=slug, pk=pk)
        except:
            raise Http404('Post does not exist')


@login_required
def post_add(request):
    if request.method == "POST":
        form = PostForm(request.POST or None, request.FILES or None)
        files = request.FILES.getlist('imgs')
        if form.is_valid():
            category = form.cleaned_data['category']
            user = request.user
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            post_obj = Post.objects.create(category=category, title=title, content=content, author=user)
            for f in files:
                Image.objects.create(post=post_obj, imgs=f)
            messages.success(request, 'Вы отправили пост на проверку :)')
        else:
            messages.error(request, 'Ошибка отправки!')
    else:
        form = PostForm()
    return render(request, 'posts/post_add.html', context={'form': form})


class CategoryList(ListView):
    model = Category
    context_object_name = 'categories'
    template_name = "posts/categories_list.html"


def category_detail(request, category_slug):
    cat = get_object_or_404(Category, slug=category_slug)
    posts = cat.post_set.all()
    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        "category": cat,
        'page_obj': page_obj
    }
    return render(request, "posts/category_detail.html", context=context)

w3xforum/templates/posts/categories_list.html
{% extends 'base_temp.html' %}
{% load posts_tags_filters %}
{% block title %}Список категорий{% endblock %}
{% block content %}
  <ol>
    {% for category in categories %}
      <li><a href="{{ category.get_absolute_url }}">{{ category.name }}({{ category|count_is_published }})</a></li>
    {% endfor %}
  </ol>
{% endblock %}

w3xforum/templates/posts/category_detail.html
{% extends 'base_list_temp.html' %}
{% load static %}
{% block title %}{{ category.name }}{% endblock %}
{% block header %}{{ category.name }}{% endblock %}

w3xforum/templates/posts/post_add.html
{% extends 'base_temp.html' %}
{% load static %}
{% block title %}Добавить пост{% endblock %}
{% block links %}
<link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock %}
{% block content %}
    {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-wrapper">
            <h2>Добавить пост</h2>
            <div class="error-text">{{ form.non_field_errors }}</div>
            {% if form.errors %}
                  {% for field in form %}
                       {% for error in field.errors %}
                            <p class="error-text">{{ error|escape }}</p>
                       {% endfor %}
                  {% endfor %}
            {% endif %}
            <div class="form-group">
                <div class="form-element">{{ form.category }}</div>
                <div class="form-element">{{ form.title }}</div>
            </div>
            <div class="form-element">{{ form.content }}</div>
            {{ form.imgs.label_tag }}
            <div class="form-element">{{ form.imgs }}</div>
      <button type="submit" class="btn button">Отправить</button>
    </form>
{% endblock %}

w3xforum/templates/posts/post_detail.html
{% extends 'base_temp.html' %}
{% block title %}{{ current_post.title }}{% endblock %}
{% block content %}
  {% include '_inc/_cat_navbar.html' %}
    {% if current_post.is_published %}
      <div>
        <ul>
          <li>
            {{ current_post.title }}
          </li>
          <li>
            {{ current_post.category }}
          </li>
          {% if current_post.image_set.all %}
            {% for images in current_post.image_set.all %}
              <li><img src="{{ images.imgs.url }}" alt="-" width="300px" height="250px"></li>
            {% endfor %}
          {% endif %}
          <li>
            {{ current_post.content }}
          </li>
          <li>
            {{ current_post.author }}
          </li>
          <li>
            Опубликовано: {{ current_post.published }}   Отредактировано: {{ current_post.edited }}
          </li>
          <li>
            <a href="/posts/" alt="-">Назад</a>
          </li>
        </ul>
      </div>
    {% endif %}
{% endblock %}

w3xforum/templates/posts/posts_list.html
{% extends 'base_list_temp.html' %}
{% load static %}
{% block title %}Список постов{% endblock %}
{% block header %}Список постов{% endblock %}